# Generated by Django 4.1.10 on 2023-08-31 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0003_alter_groupmember_emails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Snippets',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='name',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='emails',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='emails',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
