# Generated by Django 4.1.10 on 2023-08-31 18:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0004_delete_groups_delete_snippets_groupmember_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupMember',
            new_name='EmailGroup',
        ),
    ]
