# Generated by Django 4.1.10 on 2023-08-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_groupmember_emailgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailGroup',
        ),
    ]
