# Generated by Django 4.1.10 on 2023-09-01 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Home', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgroup',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='MemberInGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupsInIt', models.ManyToManyField(to='auth.group')),
            ],
        ),
    ]
