# Generated by Django 4.1.10 on 2023-09-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_emailgroup_created_date_memberingroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberingroups',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
