# Generated by Django 4.1.10 on 2023-09-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_deletedgroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedgroups',
            name='groupsDeleted',
        ),
        migrations.AddField(
            model_name='deletedgroups',
            name='listOfGroups',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
