# Generated by Django 4.1.10 on 2023-09-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_remove_deletedgroups_groupsdeleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedgroups',
            name='listOfGroups',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
