# Generated by Django 4.1.10 on 2023-09-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_deletedgroups_listofgroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedgroups',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
