# Generated by Django 4.1.10 on 2023-09-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_alter_deletedgroups_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedgroups',
            name='listOfGroups',
            field=models.JSONField(default=dict),
        ),
    ]
