# Generated by Django 4.1.10 on 2023-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_alter_deletedgroups_listofgroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedgroups',
            name='listOfGroups',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
